### ISSUE TITLE
pagination.py

### ISSUE THREAD

**Issue by ngmisl** [TransposeData/transpose-python-sdk#12]
### Component

General SDK

### Have you ensured that you have the latest version of the SDK?

- [X] transpose-data

### Operating System

Linux

### Describe the issue you are facing

using python3.10

trying to run pagination.py demo:

```

Traceback (most recent call last):
  
File "/home/x/dev/python/ens-data/main.py", line 19, in <module>
    main()
  File "/home/x/dev/python/ens-data/main.py", line 10, in main
    print(last_expired.ens_name)
AttributeError: 'list' object has no attribute 'ens_name'
```

**Comment by alangshur** [comment]
Hi @ngmisl. Thanks for flagging this! Went ahead and fixed it in PR #13. Will ping you when it's merged and the next SDK release is rolled out.

**Comment by Jon-Becker** [comment]
@ngmisl This has been addressed in v1.1.3, however the current release version is v1.2.0.

Thank you for the issue!
